### ISSUE TITLE
Latest vpc-resource-controller is not compatible with K8s 1.16

### ISSUE THREAD

**Issue by anarsen** [nuuday/terraform-aws-eks#2]
AWS provides a manifest for installing the vpc-resource-controller needed to run Windows containers in EKS. The steps involved with enabling Windows support are described here: https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html

Unfortunately the linked manifest uses the `apps/v1beta` API which was promoted in K8s 1.16 to `apps/v1`, effectively breaking application of the manifest:

```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vpc-resource-controller
  namespace: kube-system
```
